In [11]:
import tensorflow as tf
tf.set_random_seed(777)

#선형 회귀
x_train = [1,2,3]
y_train = [1,2,3]
W = tf.Variable(tf.random_normal([1]), name = 'weight') #가중치에 우선 랜덤수를 집어넣음
b = tf.Variable(tf.random_normal([1]), name = 'bias') #모수 랜덤
#우리의 모델
hypo = x_train*w + b

In [3]:
#cost function
cost = tf.reduce_mean(tf.square(hypo - y_train))

In [4]:
#gradientDescent
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())#그래프의 글로벌 변수 초기화(반드시 실행)

In [6]:
for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(w), sess.run(b))

0 2.823292 [2.1286771] [-0.8523567]
20 0.19035067 [1.533928] [-1.0505961]
40 0.15135698 [1.4572546] [-1.0239124]
60 0.1372696 [1.4308538] [-0.9779527]
80 0.12466871 [1.4101374] [-0.93219817]
100 0.113226034 [1.3908179] [-0.8884077]
120 0.10283363 [1.3724468] [-0.8466577]
140 0.09339521 [1.3549428] [-0.80686814]
160 0.084823035 [1.3382617] [-0.7689483]
180 0.07703761 [1.3223647] [-0.73281056]
200 0.06996683 [1.3072149] [-0.6983712]
220 0.06354501 [1.2927768] [-0.6655505]
240 0.057712615 [1.2790174] [-0.63427216]
260 0.0524155 [1.2659047] [-0.6044637]
280 0.04760464 [1.2534081] [-0.57605624]
300 0.043235257 [1.2414987] [-0.5489836]
320 0.039266944 [1.2301493] [-0.5231833]
340 0.03566285 [1.2193329] [-0.49859545]
360 0.032389563 [1.2090251] [-0.47516325]
380 0.029416703 [1.1992016] [-0.45283225]
400 0.026716745 [1.18984] [-0.4315508]
420 0.024264557 [1.1809182] [-0.41126958]
440 0.022037461 [1.1724157] [-0.39194146]
460 0.020014787 [1.1643128] [-0.37352163]
480 0.018177731 [1.1565907] [-0

In [13]:
#placeholder를 이용한 Linear regression
import tensorflow as tf
tf.set_random_seed(700)

In [16]:
W = tf.Variable(tf.random_normal([1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
X = tf.placeholder(tf.float32, shape = [None]) #그래프에서 특정 값을 지정하는 것이 아니라 session을 실행할때 값을 지정해줌
Y = tf.placeholder(tf.float32, shape = [None])
hypothesis = X*W+b

In [17]:
#cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [19]:
#gradientdescent optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [22]:
for step in range(2001):
    cost_val, W_val, b_val, _ = \
        sess.run([cost, W, b, train],
                feed_dict = {X : [1,2,3], Y : [1,2,3]})
    if step % 20 ==0:
        print(step, cost_val, W_val, b_val)

0 3.6702922e-06 [0.99778026] [0.00504595]
20 3.3333201e-06 [0.99788463] [0.00480881]
40 3.027185e-06 [0.99798405] [0.0045828]
60 2.7494968e-06 [0.9980788] [0.0043674]
80 2.4972721e-06 [0.998169] [0.00416217]
100 2.2680874e-06 [0.9982551] [0.0039666]
120 2.0598209e-06 [0.9983371] [0.00378019]
140 1.8707318e-06 [0.99841523] [0.00360254]
160 1.6990042e-06 [0.9984897] [0.00343324]
180 1.5431442e-06 [0.99856067] [0.00327188]
200 1.4015295e-06 [0.9986283] [0.00311813]
220 1.2729146e-06 [0.9986928] [0.00297159]
240 1.1559858e-06 [0.9987542] [0.00283195]
260 1.0499976e-06 [0.99881274] [0.00269886]
280 9.5357404e-07 [0.9988685] [0.00257204]
300 8.660533e-07 [0.99892175] [0.00245118]
320 7.86625e-07 [0.9989724] [0.002336]
340 7.143606e-07 [0.9990207] [0.00222622]
360 6.4893976e-07 [0.99906665] [0.00212164]
380 5.8932454e-07 [0.99911046] [0.00202196]
400 5.351937e-07 [0.9991523] [0.00192696]
420 4.8617125e-07 [0.9991921] [0.00183644]
440 4.4157537e-07 [0.9992301] [0.00175014]
460 4.0098234e-07 [0

In [24]:
#test model
print(sess.run(hypothesis, feed_dict = {X : [5]}))
print(sess.run(hypothesis, feed_dict = {X : [2.5]}))
print(sess.run(hypothesis, feed_dict = {X : [1.5, 3.5]}))

[4.999951]
[2.4999962]
[1.5000144 3.499978 ]


In [25]:
#다른 모수로 훈련
for step in range(2001):
    cost_val, W_val, b_val, _ = \
        sess.run([cost, W, b, train],
                 feed_dict={X: [1, 2, 3, 4, 5],
                            Y: [2.1, 3.1, 4.1, 5.1, 6.1]})
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 1.210028 [1.0659834] [0.02204183]
20 0.1659119 [1.2625597] [0.14828351]
40 0.14487396 [1.2462718] [0.2108635]
60 0.12651944 [1.2301474] [0.26909488]
80 0.11049042 [1.2150749] [0.32351145]
100 0.09649209 [1.2009894] [0.3743643]
120 0.08426732 [1.1878265] [0.4218867]
140 0.0735913 [1.1755257] [0.46629688]
160 0.0642678 [1.1640302] [0.5077987]
180 0.056125514 [1.1532876] [0.5465826]
200 0.04901484 [1.1432488] [0.5828263]
220 0.04280498 [1.1338673] [0.6166965]
240 0.037381873 [1.1251003] [0.64834857]
260 0.03264587 [1.1169072] [0.6779276]
280 0.02850991 [1.1092509] [0.7055693]
300 0.024897952 [1.1020961] [0.7314008]
320 0.02174357 [1.0954098] [0.7555406]
340 0.018988801 [1.0891613] [0.77809954]
360 0.016583066 [1.083322] [0.7991811]
380 0.014482126 [1.0778652] [0.81888187]
400 0.012647355 [1.0727657] [0.8372925]
420 0.011044994 [1.0680002] [0.8544975]
440 0.009645677 [1.0635468] [0.8705758]
460 0.0084236385 [1.0593851] [0.885601]
480 0.0073564323 [1.0554959] [0.8996421]
500 0.006424427 [

In [26]:
print(sess.run(hypothesis, feed_dict={X: [5]}))
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, feed_dict={X: [1.5, 3.5]}))


[6.1004486]
[3.5996416]
[2.5993187 4.599964 ]


In [43]:
#multivariate linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [44]:
#graph 생성
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [45]:
#session실행
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  70.09713 
Prediction:
 [[156.10497]
 [195.14879]
 [188.43814]
 [205.03168]
 [150.82404]]
10 Cost:  3.3463356 
Prediction:
 [[148.88539]
 [186.45827]
 [179.88206]
 [195.71349]
 [144.1928 ]]
20 Cost:  3.328649 
Prediction:
 [[148.87047]
 [186.42726]
 [179.85829]
 [195.68677]
 [144.16656]]
30 Cost:  3.3116531 
Prediction:
 [[148.87733]
 [186.42245]
 [179.86037]
 [195.6882 ]
 [144.16035]]
40 Cost:  3.294744 
Prediction:
 [[148.88423]
 [186.41772]
 [179.86247]
 [195.68965]
 [144.15419]]
50 Cost:  3.277942 
Prediction:
 [[148.8911 ]
 [186.413  ]
 [179.86458]
 [195.69113]
 [144.14806]]
60 Cost:  3.2612255 
Prediction:
 [[148.89796]
 [186.40831]
 [179.86668]
 [195.6926 ]
 [144.14194]]
70 Cost:  3.2445831 
Prediction:
 [[148.90482]
 [186.40363]
 [179.8688 ]
 [195.69408]
 [144.13583]]
80 Cost:  3.228043 
Prediction:
 [[148.91164]
 [186.39894]
 [179.8709 ]
 [195.69553]
 [144.12975]]
90 Cost:  3.2115884 
Prediction:
 [[148.91844]
 [186.39427]
 [179.87297]
 [195.69698]
 [144.12367]]
100 Co

980 Cost:  2.0530272 
Prediction:
 [[149.45625]
 [186.0261 ]
 [180.03838]
 [195.81181]
 [143.6446 ]]
990 Cost:  2.0429277 
Prediction:
 [[149.46158]
 [186.02243]
 [180.04002]
 [195.81294]
 [143.63985]]
1000 Cost:  2.0328727 
Prediction:
 [[149.46692]
 [186.0188 ]
 [180.04167]
 [195.81407]
 [143.63512]]
1010 Cost:  2.0228686 
Prediction:
 [[149.47223]
 [186.01515]
 [180.04329]
 [195.8152 ]
 [143.63039]]
1020 Cost:  2.0129402 
Prediction:
 [[149.47752]
 [186.01154]
 [180.04494]
 [195.81633]
 [143.62569]]
1030 Cost:  2.003043 
Prediction:
 [[149.48282]
 [186.00793]
 [180.04654]
 [195.81747]
 [143.62099]]
1040 Cost:  1.9932194 
Prediction:
 [[149.48807]
 [186.0043 ]
 [180.04816]
 [195.81857]
 [143.6163 ]]
1050 Cost:  1.9834398 
Prediction:
 [[149.49332]
 [186.00072]
 [180.04977]
 [195.81969]
 [143.61162]]
1060 Cost:  1.9737065 
Prediction:
 [[149.49857]
 [185.99713]
 [180.05139]
 [195.8208 ]
 [143.60696]]
1070 Cost:  1.9640404 
Prediction:
 [[149.50378]
 [185.99355]
 [180.053  ]
 [195.8219

1880 Cost:  1.3313739 
Prediction:
 [[149.88345]
 [185.73373]
 [180.16988]
 [195.90215]
 [143.26503]]
1890 Cost:  1.3251566 
Prediction:
 [[149.88763]
 [185.73085]
 [180.17114]
 [195.90302]
 [143.26129]]
1900 Cost:  1.3189986 
Prediction:
 [[149.8918 ]
 [185.72798]
 [180.17244]
 [195.90388]
 [143.2576 ]]
1910 Cost:  1.3128558 
Prediction:
 [[149.89597]
 [185.72514]
 [180.1737 ]
 [195.90477]
 [143.25389]]
1920 Cost:  1.3067554 
Prediction:
 [[149.90012]
 [185.72229]
 [180.17499]
 [195.90562]
 [143.25021]]
1930 Cost:  1.3006742 
Prediction:
 [[149.90427]
 [185.71945]
 [180.17627]
 [195.90652]
 [143.24654]]
1940 Cost:  1.2946278 
Prediction:
 [[149.90842]
 [185.71664]
 [180.17755]
 [195.90738]
 [143.24287]]
1950 Cost:  1.2886251 
Prediction:
 [[149.91254]
 [185.71382]
 [180.17883]
 [195.90826]
 [143.23923]]
1960 Cost:  1.282647 
Prediction:
 [[149.91664]
 [185.71101]
 [180.18008]
 [195.90912]
 [143.23557]]
1970 Cost:  1.2767127 
Prediction:
 [[149.92075]
 [185.70822]
 [180.18135]
 [195.90

In [47]:
#데이터를 파일에서 가져와서 사용하는 방법
import tensorflow as tf
import numpy as np 
tf.set_random_seed(777)

In [50]:
xy = np.loadtxt('C:/Users/admin/Desktop/새홀리기/data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [51]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))



0 Cost:  317743.8 
Prediction:
 [[-376.8061 ]
 [-450.9517 ]
 [-445.39957]
 [-485.6936 ]
 [-342.65848]
 [-252.81718]
 [-364.6057 ]
 [-271.9438 ]
 [-421.4727 ]
 [-391.21475]
 [-350.0585 ]
 [-344.3739 ]
 [-459.6417 ]
 [-381.0061 ]
 [-366.01608]
 [-458.3146 ]
 [-361.50107]
 [-438.64688]
 [-438.40005]
 [-392.45856]
 [-427.28372]
 [-423.60983]
 [-407.36307]
 [-378.6381 ]
 [-467.5096 ]]
10 Cost:  33.145496 
Prediction:
 [[149.51721 ]
 [181.64459 ]
 [177.90515 ]
 [193.13855 ]
 [139.7954  ]
 [102.886055]
 [143.53163 ]
 [104.769035]
 [169.74185 ]
 [156.40735 ]
 [139.50067 ]
 [138.34592 ]
 [184.31221 ]
 [154.29988 ]
 [144.45825 ]
 [183.62712 ]
 [148.3016  ]
 [171.17038 ]
 [175.51634 ]
 [156.85092 ]
 [168.5864  ]
 [169.85591 ]
 [160.75008 ]
 [152.0074  ]
 [188.09984 ]]
20 Cost:  17.903131 
Prediction:
 [[153.14897 ]
 [186.01291 ]
 [182.20709 ]
 [197.83022 ]
 [143.12239 ]
 [105.349365]
 [147.05229 ]
 [107.39123 ]
 [173.83308 ]
 [160.21155 ]
 [142.88692 ]
 [141.68878 ]
 [188.75009 ]
 [157.97992 ]
 [

360 Cost:  15.583483 
Prediction:
 [[153.03496 ]
 [185.96597 ]
 [182.09741 ]
 [197.91835 ]
 [142.9376  ]
 [105.543945]
 [147.40178 ]
 [108.04401 ]
 [174.06377 ]
 [160.8922  ]
 [143.03722 ]
 [141.95631 ]
 [188.42532 ]
 [157.4185  ]
 [148.38385 ]
 [188.20793 ]
 [151.04039 ]
 [175.92876 ]
 [179.38914 ]
 [160.34494 ]
 [173.062   ]
 [174.11319 ]
 [164.94818 ]
 [155.04771 ]
 [192.46265 ]]
370 Cost:  15.52342 
Prediction:
 [[153.03133]
 [185.96367]
 [182.0936 ]
 [197.91994]
 [142.93164]
 [105.5486 ]
 [147.41084]
 [108.06172]
 [174.06906]
 [160.90988]
 [143.0407 ]
 [141.96286]
 [188.41559]
 [157.40236]
 [148.39389]
 [188.21085]
 [151.01874]
 [175.94278]
 [179.37862]
 [160.33635]
 [173.07089]
 [174.11646]
 [164.95486]
 [155.03056]
 [192.45724]]
380 Cost:  15.463779 
Prediction:
 [[153.02774 ]
 [185.96138 ]
 [182.08984 ]
 [197.92151 ]
 [142.92572 ]
 [105.553215]
 [147.4199  ]
 [108.079384]
 [174.07433 ]
 [160.92749 ]
 [143.04419 ]
 [141.96938 ]
 [188.40588 ]
 [157.3863  ]
 [148.40392 ]
 [188.213

780 Cost:  13.391323 
Prediction:
 [[152.90294]
 [185.86914]
 [181.952  ]
 [197.98154]
 [142.69621]
 [105.71495]
 [147.76117]
 [108.74498]
 [174.25829]
 [161.56757]
 [143.1743 ]
 [142.2037 ]
 [188.04884]
 [156.79216]
 [148.77864]
 [188.31526]
 [150.1938 ]
 [176.48592]
 [178.98543]
 [160.01726]
 [173.41353]
 [174.23485]
 [165.21487]
 [154.38948]
 [192.24794]]
790 Cost:  13.346569 
Prediction:
 [[152.90025]
 [185.86684]
 [181.94885]
 [197.98294]
 [142.69067]
 [105.71847]
 [147.7692 ]
 [108.76064]
 [174.26224]
 [161.58205]
 [143.17732]
 [142.20895]
 [188.04063]
 [156.77844]
 [148.78737]
 [188.31747]
 [150.17513]
 [176.49841]
 [178.97668]
 [160.01021]
 [173.42133]
 [174.23737]
 [165.22086]
 [154.37526]
 [192.2431 ]]
800 Cost:  13.302115 
Prediction:
 [[152.89761]
 [185.86453]
 [181.94572]
 [197.9844 ]
 [142.68515]
 [105.72194]
 [147.7772 ]
 [108.77625]
 [174.2662 ]
 [161.59648]
 [143.18034]
 [142.21416]
 [188.03247]
 [156.76479]
 [148.79608]
 [188.31966]
 [150.15652]
 [176.51088]
 [178.968

1010 Cost:  12.43586 
Prediction:
 [[152.84633 ]
 [185.81621 ]
 [181.88329 ]
 [198.01372 ]
 [142.57123 ]
 [105.789635]
 [147.94019 ]
 [109.09382 ]
 [174.34303 ]
 [161.88399 ]
 [143.24132 ]
 [142.31747 ]
 [187.86829 ]
 [156.48969 ]
 [148.97256 ]
 [188.36224 ]
 [149.78033 ]
 [176.76497 ]
 [178.79393 ]
 [159.86371 ]
 [173.58754 ]
 [174.28877 ]
 [165.34898 ]
 [154.0782  ]
 [192.14015 ]]
1020 Cost:  12.397649 
Prediction:
 [[152.8441  ]
 [185.8139  ]
 [181.88046 ]
 [198.01508 ]
 [142.56592 ]
 [105.79262 ]
 [147.94771 ]
 [109.108475]
 [174.3464  ]
 [161.89696 ]
 [143.24411 ]
 [142.32211 ]
 [187.86082 ]
 [156.47713 ]
 [148.98067 ]
 [188.3641  ]
 [149.76308 ]
 [176.77672 ]
 [178.78604 ]
 [159.8574  ]
 [173.59485 ]
 [174.29095 ]
 [165.35461 ]
 [154.06538 ]
 [192.1356  ]]
1030 Cost:  12.359686 
Prediction:
 [[152.84187]
 [185.81161]
 [181.87766]
 [198.01645]
 [142.56061]
 [105.79556]
 [147.9552 ]
 [109.12307]
 [174.34978]
 [161.90988]
 [143.24692]
 [142.32672]
 [187.85338]
 [156.46463]
 [148.988

1290 Cost:  11.458083 
Prediction:
 [[152.79004 ]
 [185.75235 ]
 [181.80875 ]
 [198.05078 ]
 [142.42583 ]
 [105.865234]
 [148.14268 ]
 [109.48818 ]
 [174.42868 ]
 [162.22499 ]
 [143.31607 ]
 [142.43817 ]
 [187.66998 ]
 [156.15556 ]
 [149.18964 ]
 [188.40988 ]
 [149.31955 ]
 [177.08197 ]
 [178.58546 ]
 [159.69824 ]
 [173.78354 ]
 [174.34416 ]
 [165.50174 ]
 [153.74013 ]
 [192.01752 ]]
1300 Cost:  11.426476 
Prediction:
 [[152.78825]
 [185.75008]
 [181.80626]
 [198.05205]
 [142.42076]
 [105.86766]
 [148.14961]
 [109.50169]
 [174.43141]
 [162.23634]
 [143.31862]
 [142.44214]
 [187.6633 ]
 [156.14427]
 [149.19704]
 [188.41139]
 [149.30391]
 [177.09285]
 [178.57848]
 [159.69273]
 [173.7902 ]
 [174.34595]
 [165.507  ]
 [153.72884]
 [192.01329]]
1310 Cost:  11.395078 
Prediction:
 [[152.7865  ]
 [185.7478  ]
 [181.80376 ]
 [198.05334 ]
 [142.41571 ]
 [105.870056]
 [148.15652 ]
 [109.51516 ]
 [174.43413 ]
 [162.24763 ]
 [143.32114 ]
 [142.44609 ]
 [187.65665 ]
 [156.13303 ]
 [149.20439 ]
 [188

1510 Cost:  10.809268 
Prediction:
 [[152.7543 ]
 [185.70285]
 [181.75644]
 [198.07831]
 [142.31667]
 [105.91431]
 [148.29076]
 [109.77638]
 [174.48413]
 [162.46251]
 [143.36996]
 [142.52081]
 [187.5291 ]
 [155.91685]
 [149.34677]
 [188.44087]
 [148.98747]
 [177.31468]
 [178.4387 ]
 [159.58296]
 [173.9262 ]
 [174.3807 ]
 [165.61421]
 [153.50273]
 [191.92732]]
1520 Cost:  10.781985 
Prediction:
 [[152.75284]
 [185.70062]
 [181.75418]
 [198.07953]
 [142.31181]
 [105.91634]
 [148.29729]
 [109.78906]
 [174.48642]
 [162.47272]
 [143.37233]
 [142.52432]
 [187.523  ]
 [155.90648]
 [149.35365]
 [188.44215]
 [148.97298]
 [177.32495]
 [178.43237]
 [159.57802]
 [173.93246]
 [174.38223]
 [165.61917]
 [153.49251]
 [191.92334]]
1530 Cost:  10.754887 
Prediction:
 [[152.75139]
 [185.69841]
 [181.75194]
 [198.08076]
 [142.30696]
 [105.91836]
 [148.30377]
 [109.8017 ]
 [174.4887 ]
 [162.48288]
 [143.37468]
 [142.52783]
 [187.51689]
 [155.89613]
 [149.3605 ]
 [188.44344]
 [148.95851]
 [177.33516]
 [178.

1860 Cost:  9.953706 
Prediction:
 [[152.71056]
 [185.62581]
 [181.68324]
 [198.11943]
 [142.15202]
 [105.97633]
 [148.508  ]
 [110.19888]
 [174.55397]
 [162.79199]
 [143.44786]
 [142.63309]
 [187.32906]
 [155.5757 ]
 [149.5747 ]
 [188.48016]
 [148.5081 ]
 [177.65758]
 [178.23256]
 [159.42307]
 [174.1345 ]
 [174.42802]
 [165.7804 ]
 [153.17024]
 [191.79424]]
1870 Cost:  9.932016 
Prediction:
 [[152.7095  ]
 [185.62363 ]
 [181.68134 ]
 [198.12054 ]
 [142.14748 ]
 [105.977844]
 [148.5139  ]
 [110.21034 ]
 [174.55568 ]
 [162.8006  ]
 [143.44995 ]
 [142.63597 ]
 [187.32375 ]
 [155.5666  ]
 [149.58086 ]
 [188.48114 ]
 [148.49522 ]
 [177.6669  ]
 [178.22711 ]
 [159.41888 ]
 [174.14014 ]
 [174.4292  ]
 [165.78494 ]
 [153.16148 ]
 [191.7906  ]]
1880 Cost:  9.91049 
Prediction:
 [[152.70848]
 [185.62148]
 [181.6794 ]
 [198.12166]
 [142.14294]
 [105.97934]
 [148.51978]
 [110.22176]
 [174.55736]
 [162.80919]
 [143.45203]
 [142.63884]
 [187.31845]
 [155.55753]
 [149.58696]
 [188.48209]
 [148.48239

In [53]:
#queue runner를 이용한 linear regression
import tensorflow as tf
tf.set_random_seed(777)

In [56]:
filename_queue = tf.train.string_input_producer(
    ['C:/Users/admin/Desktop/새홀리기/data-01-test-score.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [59]:
record_defaults = [
    [0.],[0.],[0.],[0.]
] #실수형으로 지정
xy = tf.decode_csv(value, record_defaults = record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10) #queue에 있는 데이터에서 10개씩 batch에 넣어줌

In [60]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())



In [62]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))



0 Cost:  57.701935 
Prediction:
 [[179.5309  ]
 [178.09631 ]
 [192.26291 ]
 [137.89763 ]
 [ 99.016235]
 [142.16782 ]
 [102.96337 ]
 [165.32483 ]
 [149.3363  ]
 [138.07399 ]]
10 Cost:  42.44353 
Prediction:
 [[170.09198]
 [153.77866]
 [142.01122]
 [138.50662]
 [190.7878 ]
 [160.89981]
 [146.44505]
 [185.95474]
 [154.62144]
 [174.85745]]
20 Cost:  42.061165 
Prediction:
 [[170.14238]
 [153.8536 ]
 [142.04083]
 [138.55023]
 [190.79654]
 [160.89157]
 [146.48634]
 [185.99734]
 [154.60612]
 [174.90358]]
30 Cost:  41.733612 
Prediction:
 [[170.16608]
 [153.90367]
 [142.04839]
 [138.57204]
 [190.77643]
 [160.85942]
 [146.50465]
 [186.01099]
 [154.56802]
 [174.92221]]
40 Cost:  41.40925 
Prediction:
 [[170.18947]
 [153.95337]
 [142.0558 ]
 [138.59361]
 [190.75621]
 [160.82726]
 [146.5227 ]
 [186.02437]
 [154.52994]
 [174.94061]]
50 Cost:  41.087715 
Prediction:
 [[170.21274]
 [154.0028 ]
 [142.06316]
 [138.61507]
 [190.73608]
 [160.7952 ]
 [146.5407 ]
 [186.0377 ]
 [154.49199]
 [174.95895]]
60 

510 Cost:  28.988043 
Prediction:
 [[171.16302]
 [156.04337]
 [142.37112]
 [139.49692]
 [189.89804]
 [159.45801]
 [147.29684]
 [186.5822 ]
 [152.89908]
 [175.74356]]
520 Cost:  28.775776 
Prediction:
 [[171.18127]
 [156.08302]
 [142.3772 ]
 [139.51398]
 [189.8816 ]
 [159.43173]
 [147.31184]
 [186.59265]
 [152.86755]
 [175.75938]]
530 Cost:  28.56532 
Prediction:
 [[171.19942]
 [156.12248]
 [142.38324]
 [139.53096]
 [189.86525]
 [159.40555]
 [147.32677]
 [186.60307]
 [152.83617]
 [175.77519]]
540 Cost:  28.356771 
Prediction:
 [[171.21748]
 [156.16174]
 [142.38927]
 [139.54784]
 [189.84895]
 [159.37947]
 [147.34164]
 [186.6134 ]
 [152.80489]
 [175.79092]]
550 Cost:  28.149988 
Prediction:
 [[171.23544]
 [156.20084]
 [142.39526]
 [139.56465]
 [189.83275]
 [159.35352]
 [147.35646]
 [186.62373]
 [152.77374]
 [175.80664]]
560 Cost:  27.94511 
Prediction:
 [[171.2533 ]
 [156.23973]
 [142.40125]
 [139.58138]
 [189.81657]
 [159.32767]
 [147.37122]
 [186.63394]
 [152.74269]
 [175.82227]]
570 Co

1040 Cost:  19.960428 
Prediction:
 [[172.00935]
 [157.90688]
 [142.66116]
 [140.29486]
 [189.11792]
 [158.20583]
 [148.01683]
 [187.06784]
 [151.38736]
 [176.51952]]
1050 Cost:  19.827358 
Prediction:
 [[172.02316]
 [157.93774]
 [142.66606]
 [140.308  ]
 [189.10483]
 [158.18475]
 [148.02905]
 [187.07574]
 [151.36172]
 [176.53299]]
1060 Cost:  19.695484 
Prediction:
 [[172.0369 ]
 [157.96848]
 [142.67093]
 [140.32108]
 [189.0918 ]
 [158.16379]
 [148.04123]
 [187.08365]
 [151.3362 ]
 [176.54639]]
1070 Cost:  19.564772 
Prediction:
 [[172.05054]
 [157.99905]
 [142.6758 ]
 [140.3341 ]
 [189.07886]
 [158.1429 ]
 [148.05338]
 [187.09149]
 [151.31076]
 [176.55978]]
1080 Cost:  19.43517 
Prediction:
 [[172.06413]
 [158.0295 ]
 [142.68063]
 [140.34705]
 [189.06593]
 [158.12209]
 [148.06546]
 [187.09929]
 [151.28543]
 [176.57312]]
1090 Cost:  19.306742 
Prediction:
 [[172.07764]
 [158.05978]
 [142.68544]
 [140.35992]
 [189.05307]
 [158.10138]
 [148.0775 ]
 [187.10706]
 [151.2602 ]
 [176.58641]]

1590 Cost:  14.134638 
Prediction:
 [[172.66861]
 [159.40549]
 [142.90315]
 [140.92921]
 [188.47578]
 [157.16794]
 [148.62506]
 [187.44685]
 [150.11493]
 [177.20262]]
1600 Cost:  14.052673 
Prediction:
 [[172.67886]
 [159.42929]
 [142.90709]
 [140.93922]
 [188.46547]
 [157.15117]
 [148.635  ]
 [187.45276]
 [150.0942 ]
 [177.21404]]
1610 Cost:  13.97141 
Prediction:
 [[172.68909]
 [159.45297]
 [142.911  ]
 [140.94919]
 [188.45517]
 [157.13446]
 [148.6449 ]
 [187.45865]
 [150.07355]
 [177.22539]]
1620 Cost:  13.890882 
Prediction:
 [[172.69922]
 [159.47653]
 [142.91487]
 [140.95909]
 [188.44492]
 [157.11783]
 [148.65474]
 [187.4645 ]
 [150.05296]
 [177.23671]]
1630 Cost:  13.811055 
Prediction:
 [[172.70932]
 [159.49998]
 [142.91875]
 [140.96893]
 [188.43472]
 [157.10126]
 [148.66457]
 [187.4703 ]
 [150.03246]
 [177.248  ]]
1640 Cost:  13.731878 
Prediction:
 [[172.71938]
 [159.52335]
 [142.92262]
 [140.97874]
 [188.42456]
 [157.08476]
 [148.67436]
 [187.47609]
 [150.01204]
 [177.2593 ]]